version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-server

  node-server:
    build: ./
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    depends_on:
      - redis

  redis:
    image: redis

volumes:
  mongo-db:
